// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/widgets/settings_sheet_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:frontend/data/models/team.dart' as _i2;
import 'package:frontend/data/repositories/team_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTeam_0 extends _i1.SmartFake implements _i2.Team {
  _FakeTeam_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TeamRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTeamRepository extends _i1.Mock implements _i3.TeamRepository {
  @override
  _i4.Future<_i2.Team> createTeam({
    required String? name,
    required String? createdBy,
    bool? isMasterTeam = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTeam, [], {
              #name: name,
              #createdBy: createdBy,
              #isMasterTeam: isMasterTeam,
            }),
            returnValue: _i4.Future<_i2.Team>.value(
              _FakeTeam_0(
                this,
                Invocation.method(#createTeam, [], {
                  #name: name,
                  #createdBy: createdBy,
                  #isMasterTeam: isMasterTeam,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Team>.value(
              _FakeTeam_0(
                this,
                Invocation.method(#createTeam, [], {
                  #name: name,
                  #createdBy: createdBy,
                  #isMasterTeam: isMasterTeam,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Team>);

  @override
  _i4.Future<_i2.Team?> joinTeamByCode({
    required String? inviteCode,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#joinTeamByCode, [], {
              #inviteCode: inviteCode,
              #userId: userId,
            }),
            returnValue: _i4.Future<_i2.Team?>.value(),
            returnValueForMissingStub: _i4.Future<_i2.Team?>.value(),
          )
          as _i4.Future<_i2.Team?>);

  @override
  _i4.Future<void> leaveTeam({
    required String? teamId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#leaveTeam, [], {
              #teamId: teamId,
              #userId: userId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Team?> getTeam(String? teamId) =>
      (super.noSuchMethod(
            Invocation.method(#getTeam, [teamId]),
            returnValue: _i4.Future<_i2.Team?>.value(),
            returnValueForMissingStub: _i4.Future<_i2.Team?>.value(),
          )
          as _i4.Future<_i2.Team?>);

  @override
  _i4.Future<List<_i2.Team>> getUserTeams(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserTeams, [userId]),
            returnValue: _i4.Future<List<_i2.Team>>.value(<_i2.Team>[]),
            returnValueForMissingStub: _i4.Future<List<_i2.Team>>.value(
              <_i2.Team>[],
            ),
          )
          as _i4.Future<List<_i2.Team>>);

  @override
  _i4.Future<_i2.TeamSettings?> getTeamSettings(String? teamId) =>
      (super.noSuchMethod(
            Invocation.method(#getTeamSettings, [teamId]),
            returnValue: _i4.Future<_i2.TeamSettings?>.value(),
            returnValueForMissingStub: _i4.Future<_i2.TeamSettings?>.value(),
          )
          as _i4.Future<_i2.TeamSettings?>);

  @override
  _i4.Future<void> updateTeamSettings({
    required String? teamId,
    String? defaultEventCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTeamSettings, [], {
              #teamId: teamId,
              #defaultEventCode: defaultEventCode,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String> setTeamSheet({
    required String? teamId,
    required String? sheetId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setTeamSheet, [], {
              #teamId: teamId,
              #sheetId: sheetId,
            }),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#setTeamSheet, [], {
                  #teamId: teamId,
                  #sheetId: sheetId,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#setTeamSheet, [], {
                  #teamId: teamId,
                  #sheetId: sheetId,
                }),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<Map<String, dynamic>> backfillEventToSheets({
    required String? eventId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#backfillEventToSheets, [], {#eventId: eventId}),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> regenerateInviteCode({
    required String? teamId,
    required String? requestingUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#regenerateInviteCode, [], {
              #teamId: teamId,
              #requestingUserId: requestingUserId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
