// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/presentation/screens/auth/team_select_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:firebase_auth/firebase_auth.dart' as _i3;
import 'package:frontend/core/auth/auth_service.dart' as _i8;
import 'package:frontend/data/models/team.dart' as _i2;
import 'package:frontend/data/models/user_profile.dart' as _i4;
import 'package:frontend/data/repositories/auth_repository.dart' as _i9;
import 'package:frontend/data/repositories/team_repository.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTeam_0 extends _i1.SmartFake implements _i2.Team {
  _FakeTeam_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserCredential_1 extends _i1.SmartFake
    implements _i3.UserCredential {
  _FakeUserCredential_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserProfile_2 extends _i1.SmartFake implements _i4.UserProfile {
  _FakeUserProfile_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TeamRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTeamRepository extends _i1.Mock implements _i5.TeamRepository {
  @override
  _i6.Future<_i2.Team> createTeam({
    required String? name,
    required String? createdBy,
    bool? isMasterTeam = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTeam, [], {
              #name: name,
              #createdBy: createdBy,
              #isMasterTeam: isMasterTeam,
            }),
            returnValue: _i6.Future<_i2.Team>.value(
              _FakeTeam_0(
                this,
                Invocation.method(#createTeam, [], {
                  #name: name,
                  #createdBy: createdBy,
                  #isMasterTeam: isMasterTeam,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Team>.value(
              _FakeTeam_0(
                this,
                Invocation.method(#createTeam, [], {
                  #name: name,
                  #createdBy: createdBy,
                  #isMasterTeam: isMasterTeam,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.Team>);

  @override
  _i6.Future<_i2.Team?> joinTeamByCode({
    required String? inviteCode,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#joinTeamByCode, [], {
              #inviteCode: inviteCode,
              #userId: userId,
            }),
            returnValue: _i6.Future<_i2.Team?>.value(),
            returnValueForMissingStub: _i6.Future<_i2.Team?>.value(),
          )
          as _i6.Future<_i2.Team?>);

  @override
  _i6.Future<void> leaveTeam({
    required String? teamId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#leaveTeam, [], {
              #teamId: teamId,
              #userId: userId,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i2.Team?> getTeam(String? teamId) =>
      (super.noSuchMethod(
            Invocation.method(#getTeam, [teamId]),
            returnValue: _i6.Future<_i2.Team?>.value(),
            returnValueForMissingStub: _i6.Future<_i2.Team?>.value(),
          )
          as _i6.Future<_i2.Team?>);

  @override
  _i6.Future<List<_i2.Team>> getUserTeams(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserTeams, [userId]),
            returnValue: _i6.Future<List<_i2.Team>>.value(<_i2.Team>[]),
            returnValueForMissingStub: _i6.Future<List<_i2.Team>>.value(
              <_i2.Team>[],
            ),
          )
          as _i6.Future<List<_i2.Team>>);

  @override
  _i6.Future<_i2.TeamSettings?> getTeamSettings(String? teamId) =>
      (super.noSuchMethod(
            Invocation.method(#getTeamSettings, [teamId]),
            returnValue: _i6.Future<_i2.TeamSettings?>.value(),
            returnValueForMissingStub: _i6.Future<_i2.TeamSettings?>.value(),
          )
          as _i6.Future<_i2.TeamSettings?>);

  @override
  _i6.Future<void> updateTeamSettings({
    required String? teamId,
    String? defaultEventCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTeamSettings, [], {
              #teamId: teamId,
              #defaultEventCode: defaultEventCode,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String> setTeamSheet({
    required String? teamId,
    required String? sheetId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setTeamSheet, [], {
              #teamId: teamId,
              #sheetId: sheetId,
            }),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#setTeamSheet, [], {
                  #teamId: teamId,
                  #sheetId: sheetId,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#setTeamSheet, [], {
                  #teamId: teamId,
                  #sheetId: sheetId,
                }),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<Map<String, dynamic>> backfillEventToSheets({
    required String? eventId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#backfillEventToSheets, [], {#eventId: eventId}),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<void> regenerateInviteCode({
    required String? teamId,
    required String? requestingUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#regenerateInviteCode, [], {
              #teamId: teamId,
              #requestingUserId: requestingUserId,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i8.AuthService {
  @override
  _i6.Stream<_i3.User?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i6.Stream<_i3.User?>.empty(),
            returnValueForMissingStub: _i6.Stream<_i3.User?>.empty(),
          )
          as _i6.Stream<_i3.User?>);

  @override
  bool get isGoogleSignInSupported =>
      (super.noSuchMethod(
            Invocation.getter(#isGoogleSignInSupported),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i6.Future<_i3.UserCredential> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i6.Future<_i3.UserCredential>.value(
              _FakeUserCredential_1(
                this,
                Invocation.method(#signInWithGoogle, []),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i3.UserCredential>.value(
              _FakeUserCredential_1(
                this,
                Invocation.method(#signInWithGoogle, []),
              ),
            ),
          )
          as _i6.Future<_i3.UserCredential>);

  @override
  _i6.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>> forceRefreshClaims() =>
      (super.noSuchMethod(
            Invocation.method(#forceRefreshClaims, []),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<_i4.UserProfile?> getUserProfile(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, [uid]),
            returnValue: _i6.Future<_i4.UserProfile?>.value(),
            returnValueForMissingStub: _i6.Future<_i4.UserProfile?>.value(),
          )
          as _i6.Future<_i4.UserProfile?>);

  @override
  _i6.Future<_i3.UserCredential> signInWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i6.Future<_i3.UserCredential>.value(
              _FakeUserCredential_1(
                this,
                Invocation.method(#signInWithEmailAndPassword, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i3.UserCredential>.value(
              _FakeUserCredential_1(
                this,
                Invocation.method(#signInWithEmailAndPassword, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.UserCredential>);

  @override
  _i6.Future<void> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i9.AuthRepository {
  @override
  _i6.Stream<_i3.User?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i6.Stream<_i3.User?>.empty(),
            returnValueForMissingStub: _i6.Stream<_i3.User?>.empty(),
          )
          as _i6.Stream<_i3.User?>);

  @override
  _i6.Future<_i4.UserProfile> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i6.Future<_i4.UserProfile>.value(
              _FakeUserProfile_2(
                this,
                Invocation.method(#signInWithGoogle, []),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i4.UserProfile>.value(
              _FakeUserProfile_2(
                this,
                Invocation.method(#signInWithGoogle, []),
              ),
            ),
          )
          as _i6.Future<_i4.UserProfile>);

  @override
  _i6.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i4.UserProfile?> getCurrentUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUserProfile, []),
            returnValue: _i6.Future<_i4.UserProfile?>.value(),
            returnValueForMissingStub: _i6.Future<_i4.UserProfile?>.value(),
          )
          as _i6.Future<_i4.UserProfile?>);

  @override
  _i6.Future<_i4.UserProfile?> refreshUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#refreshUserProfile, []),
            returnValue: _i6.Future<_i4.UserProfile?>.value(),
            returnValueForMissingStub: _i6.Future<_i4.UserProfile?>.value(),
          )
          as _i6.Future<_i4.UserProfile?>);

  @override
  _i6.Future<void> updateCurrentTeamId(String? teamId) =>
      (super.noSuchMethod(
            Invocation.method(#updateCurrentTeamId, [teamId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
