// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:frontend/data/models/event.dart' as _i5;
import 'package:frontend/data/models/match_report.dart' as _i4;
import 'package:frontend/data/repositories/firestore_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FirestoreRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreRepository extends _i1.Mock
    implements _i2.FirestoreRepository {
  MockFirestoreRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i2.MatchesView> watchMatchesView(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#watchMatchesView, [eventId]),
            returnValue: _i3.Stream<_i2.MatchesView>.empty(),
          )
          as _i3.Stream<_i2.MatchesView>);

  @override
  _i3.Stream<List<_i4.MatchReport>> watchMatches(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#watchMatches, [eventId]),
            returnValue: _i3.Stream<List<_i4.MatchReport>>.empty(),
          )
          as _i3.Stream<List<_i4.MatchReport>>);

  @override
  _i3.Stream<List<_i4.MatchReport>> watchTrash(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#watchTrash, [eventId]),
            returnValue: _i3.Stream<List<_i4.MatchReport>>.empty(),
          )
          as _i3.Stream<List<_i4.MatchReport>>);

  @override
  _i3.Future<List<_i4.MatchReport>> getMatches(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#getMatches, [eventId]),
            returnValue: _i3.Future<List<_i4.MatchReport>>.value(
              <_i4.MatchReport>[],
            ),
          )
          as _i3.Future<List<_i4.MatchReport>>);

  @override
  _i3.Future<List<_i4.MatchReport>> getDeletedMatches(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#getDeletedMatches, [eventId]),
            returnValue: _i3.Future<List<_i4.MatchReport>>.value(
              <_i4.MatchReport>[],
            ),
          )
          as _i3.Future<List<_i4.MatchReport>>);

  @override
  _i3.Future<void> createMatch(String? eventId, _i4.MatchReport? match) =>
      (super.noSuchMethod(
            Invocation.method(#createMatch, [eventId, match]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateMatch(String? eventId, _i4.MatchReport? match) =>
      (super.noSuchMethod(
            Invocation.method(#updateMatch, [eventId, match]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> trashMatch(String? eventId, String? matchId) =>
      (super.noSuchMethod(
            Invocation.method(#trashMatch, [eventId, matchId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> restoreMatch(String? eventId, String? matchId) =>
      (super.noSuchMethod(
            Invocation.method(#restoreMatch, [eventId, matchId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteMatch(String? eventId, String? matchId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMatch, [eventId, matchId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i5.Event?> getEvent(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#getEvent, [eventId]),
            returnValue: _i3.Future<_i5.Event?>.value(),
          )
          as _i3.Future<_i5.Event?>);

  @override
  _i3.Future<List<_i5.Event>> getEvents() =>
      (super.noSuchMethod(
            Invocation.method(#getEvents, []),
            returnValue: _i3.Future<List<_i5.Event>>.value(<_i5.Event>[]),
          )
          as _i3.Future<List<_i5.Event>>);
}
