// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:drift/drift.dart' as _i4;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i5;
import 'package:frontend/data/local/database/app_database.dart' as _i2;
import 'package:frontend/data/local/sync/sync_manager.dart' as _i3;
import 'package:frontend/data/models/event.dart' as _i9;
import 'package:frontend/data/models/match_report.dart' as _i8;
import 'package:frontend/data/repositories/firestore_repository.dart' as _i10;
import 'package:frontend/data/repositories/hybrid_repository.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppDatabase_0 extends _i1.SmartFake implements _i2.AppDatabase {
  _FakeAppDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSyncStats_1 extends _i1.SmartFake implements _i3.SyncStats {
  _FakeSyncStats_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMigrationStrategy_2 extends _i1.SmartFake
    implements _i4.MigrationStrategy {
  _FakeMigrationStrategy_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$AppDatabaseManager_3 extends _i1.SmartFake
    implements _i2.$AppDatabaseManager {
  _Fake$AppDatabaseManager_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$LocalMatchReportsTable_4 extends _i1.SmartFake
    implements _i2.$LocalMatchReportsTable {
  _Fake$LocalMatchReportsTable_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$LocalEventsTable_5 extends _i1.SmartFake
    implements _i2.$LocalEventsTable {
  _Fake$LocalEventsTable_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$SyncQueueTable_6 extends _i1.SmartFake
    implements _i2.$SyncQueueTable {
  _Fake$SyncQueueTable_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$SyncConflictsTable_7 extends _i1.SmartFake
    implements _i2.$SyncConflictsTable {
  _Fake$SyncConflictsTable_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGeneratedDatabase_8 extends _i1.SmartFake
    implements _i4.GeneratedDatabase {
  _FakeGeneratedDatabase_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDriftDatabaseOptions_9 extends _i1.SmartFake
    implements _i4.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryUpdateRules_10 extends _i1.SmartFake
    implements _i4.StreamQueryUpdateRules {
  _FakeStreamQueryUpdateRules_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnection_11 extends _i1.SmartFake
    implements _i4.DatabaseConnection {
  _FakeDatabaseConnection_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryExecutor_12 extends _i1.SmartFake implements _i4.QueryExecutor {
  _FakeQueryExecutor_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryStore_13 extends _i1.SmartFake
    implements _i5.StreamQueryStore {
  _FakeStreamQueryStore_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnectionUser_14 extends _i1.SmartFake
    implements _i4.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSyncQueueStats_15 extends _i1.SmartFake
    implements _i2.SyncQueueStats {
  _FakeSyncQueueStats_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMigrator_16 extends _i1.SmartFake implements _i4.Migrator {
  _FakeMigrator_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_17<T> extends _i1.SmartFake implements _i6.Future<T> {
  _FakeFuture_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertStatement_18<T1 extends _i4.Table, D1> extends _i1.SmartFake
    implements _i4.InsertStatement<T1, D1> {
  _FakeInsertStatement_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateStatement_19<T extends _i4.Table, D> extends _i1.SmartFake
    implements _i4.UpdateStatement<T, D> {
  _FakeUpdateStatement_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSimpleSelectStatement_20<T1 extends _i4.HasResultSet, D>
    extends _i1.SmartFake
    implements _i4.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJoinedSelectStatement_21<FirstT extends _i4.HasResultSet, FirstD>
    extends _i1.SmartFake
    implements _i4.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseSelectStatement_22<Row> extends _i1.SmartFake
    implements _i4.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeleteStatement_23<T1 extends _i4.Table, D1> extends _i1.SmartFake
    implements _i4.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSelectable_24<T> extends _i1.SmartFake implements _i4.Selectable<T> {
  _FakeSelectable_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGenerationContext_25 extends _i1.SmartFake
    implements _i4.GenerationContext {
  _FakeGenerationContext_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HybridRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHybridRepository extends _i1.Mock implements _i7.HybridRepository {
  MockHybridRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLocalDbAvailable =>
      (super.noSuchMethod(
            Invocation.getter(#isLocalDbAvailable),
            returnValue: false,
          )
          as bool);

  @override
  _i2.AppDatabase get db =>
      (super.noSuchMethod(
            Invocation.getter(#db),
            returnValue: _FakeAppDatabase_0(this, Invocation.getter(#db)),
          )
          as _i2.AppDatabase);

  @override
  _i6.Stream<List<_i8.MatchReport>> watchMatches(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#watchMatches, [eventId]),
            returnValue: _i6.Stream<List<_i8.MatchReport>>.empty(),
          )
          as _i6.Stream<List<_i8.MatchReport>>);

  @override
  _i6.Stream<List<_i8.MatchReport>> watchTrash(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#watchTrash, [eventId]),
            returnValue: _i6.Stream<List<_i8.MatchReport>>.empty(),
          )
          as _i6.Stream<List<_i8.MatchReport>>);

  @override
  _i6.Future<List<_i8.MatchReport>> getMatches(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#getMatches, [eventId]),
            returnValue: _i6.Future<List<_i8.MatchReport>>.value(
              <_i8.MatchReport>[],
            ),
          )
          as _i6.Future<List<_i8.MatchReport>>);

  @override
  _i6.Future<void> createMatch(String? eventId, _i8.MatchReport? match) =>
      (super.noSuchMethod(
            Invocation.method(#createMatch, [eventId, match]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateMatch(String? eventId, _i8.MatchReport? match) =>
      (super.noSuchMethod(
            Invocation.method(#updateMatch, [eventId, match]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> trashMatch(String? eventId, String? matchId) =>
      (super.noSuchMethod(
            Invocation.method(#trashMatch, [eventId, matchId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> restoreMatch(String? eventId, String? matchId) =>
      (super.noSuchMethod(
            Invocation.method(#restoreMatch, [eventId, matchId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteMatch(String? eventId, String? matchId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMatch, [eventId, matchId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i9.Event?> getEvent(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#getEvent, [eventId]),
            returnValue: _i6.Future<_i9.Event?>.value(),
          )
          as _i6.Future<_i9.Event?>);

  @override
  _i6.Future<List<_i9.Event>> getEvents() =>
      (super.noSuchMethod(
            Invocation.method(#getEvents, []),
            returnValue: _i6.Future<List<_i9.Event>>.value(<_i9.Event>[]),
          )
          as _i6.Future<List<_i9.Event>>);

  @override
  _i6.Future<void> forceSync() =>
      (super.noSuchMethod(
            Invocation.method(#forceSync, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.SyncStats> getSyncStats() =>
      (super.noSuchMethod(
            Invocation.method(#getSyncStats, []),
            returnValue: _i6.Future<_i3.SyncStats>.value(
              _FakeSyncStats_1(this, Invocation.method(#getSyncStats, [])),
            ),
          )
          as _i6.Future<_i3.SyncStats>);

  @override
  _i6.Future<void> clearAllLocalData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllLocalData, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [FirestoreRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreRepository extends _i1.Mock
    implements _i10.FirestoreRepository {
  MockFirestoreRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<List<_i8.MatchReport>> watchMatches(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#watchMatches, [eventId]),
            returnValue: _i6.Stream<List<_i8.MatchReport>>.empty(),
          )
          as _i6.Stream<List<_i8.MatchReport>>);

  @override
  _i6.Stream<List<_i8.MatchReport>> watchTrash(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#watchTrash, [eventId]),
            returnValue: _i6.Stream<List<_i8.MatchReport>>.empty(),
          )
          as _i6.Stream<List<_i8.MatchReport>>);

  @override
  _i6.Future<List<_i8.MatchReport>> getMatches(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#getMatches, [eventId]),
            returnValue: _i6.Future<List<_i8.MatchReport>>.value(
              <_i8.MatchReport>[],
            ),
          )
          as _i6.Future<List<_i8.MatchReport>>);

  @override
  _i6.Future<List<_i8.MatchReport>> getDeletedMatches(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#getDeletedMatches, [eventId]),
            returnValue: _i6.Future<List<_i8.MatchReport>>.value(
              <_i8.MatchReport>[],
            ),
          )
          as _i6.Future<List<_i8.MatchReport>>);

  @override
  _i6.Future<void> createMatch(
    String? eventId,
    _i8.MatchReport? match, {
    String? teamIdOverride,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createMatch,
              [eventId, match],
              {#teamIdOverride: teamIdOverride},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateMatch(
    String? eventId,
    _i8.MatchReport? match, {
    String? teamIdOverride,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateMatch,
              [eventId, match],
              {#teamIdOverride: teamIdOverride},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> trashMatch(String? eventId, String? matchId) =>
      (super.noSuchMethod(
            Invocation.method(#trashMatch, [eventId, matchId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> restoreMatch(String? eventId, String? matchId) =>
      (super.noSuchMethod(
            Invocation.method(#restoreMatch, [eventId, matchId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteMatch(String? eventId, String? matchId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMatch, [eventId, matchId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i9.Event?> getEvent(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#getEvent, [eventId]),
            returnValue: _i6.Future<_i9.Event?>.value(),
          )
          as _i6.Future<_i9.Event?>);

  @override
  _i6.Future<List<_i9.Event>> getEvents() =>
      (super.noSuchMethod(
            Invocation.method(#getEvents, []),
            returnValue: _i6.Future<List<_i9.Event>>.value(<_i9.Event>[]),
          )
          as _i6.Future<List<_i9.Event>>);
}

/// A class which mocks [AppDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppDatabase extends _i1.Mock implements _i2.AppDatabase {
  MockAppDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get schemaVersion =>
      (super.noSuchMethod(Invocation.getter(#schemaVersion), returnValue: 0)
          as int);

  @override
  _i4.MigrationStrategy get migration =>
      (super.noSuchMethod(
            Invocation.getter(#migration),
            returnValue: _FakeMigrationStrategy_2(
              this,
              Invocation.getter(#migration),
            ),
          )
          as _i4.MigrationStrategy);

  @override
  _i2.$AppDatabaseManager get managers =>
      (super.noSuchMethod(
            Invocation.getter(#managers),
            returnValue: _Fake$AppDatabaseManager_3(
              this,
              Invocation.getter(#managers),
            ),
          )
          as _i2.$AppDatabaseManager);

  @override
  _i2.$LocalMatchReportsTable get localMatchReports =>
      (super.noSuchMethod(
            Invocation.getter(#localMatchReports),
            returnValue: _Fake$LocalMatchReportsTable_4(
              this,
              Invocation.getter(#localMatchReports),
            ),
          )
          as _i2.$LocalMatchReportsTable);

  @override
  _i2.$LocalEventsTable get localEvents =>
      (super.noSuchMethod(
            Invocation.getter(#localEvents),
            returnValue: _Fake$LocalEventsTable_5(
              this,
              Invocation.getter(#localEvents),
            ),
          )
          as _i2.$LocalEventsTable);

  @override
  _i2.$SyncQueueTable get syncQueue =>
      (super.noSuchMethod(
            Invocation.getter(#syncQueue),
            returnValue: _Fake$SyncQueueTable_6(
              this,
              Invocation.getter(#syncQueue),
            ),
          )
          as _i2.$SyncQueueTable);

  @override
  _i2.$SyncConflictsTable get syncConflicts =>
      (super.noSuchMethod(
            Invocation.getter(#syncConflicts),
            returnValue: _Fake$SyncConflictsTable_7(
              this,
              Invocation.getter(#syncConflicts),
            ),
          )
          as _i2.$SyncConflictsTable);

  @override
  Iterable<_i4.TableInfo<_i4.Table, Object?>> get allTables =>
      (super.noSuchMethod(
            Invocation.getter(#allTables),
            returnValue: <_i4.TableInfo<_i4.Table, Object?>>[],
          )
          as Iterable<_i4.TableInfo<_i4.Table, Object?>>);

  @override
  List<_i4.DatabaseSchemaEntity> get allSchemaEntities =>
      (super.noSuchMethod(
            Invocation.getter(#allSchemaEntities),
            returnValue: <_i4.DatabaseSchemaEntity>[],
          )
          as List<_i4.DatabaseSchemaEntity>);

  @override
  _i4.GeneratedDatabase get attachedDatabase =>
      (super.noSuchMethod(
            Invocation.getter(#attachedDatabase),
            returnValue: _FakeGeneratedDatabase_8(
              this,
              Invocation.getter(#attachedDatabase),
            ),
          )
          as _i4.GeneratedDatabase);

  @override
  _i4.DriftDatabaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeDriftDatabaseOptions_9(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i4.DriftDatabaseOptions);

  @override
  _i4.StreamQueryUpdateRules get streamUpdateRules =>
      (super.noSuchMethod(
            Invocation.getter(#streamUpdateRules),
            returnValue: _FakeStreamQueryUpdateRules_10(
              this,
              Invocation.getter(#streamUpdateRules),
            ),
          )
          as _i4.StreamQueryUpdateRules);

  @override
  _i4.DatabaseConnection get connection =>
      (super.noSuchMethod(
            Invocation.getter(#connection),
            returnValue: _FakeDatabaseConnection_11(
              this,
              Invocation.getter(#connection),
            ),
          )
          as _i4.DatabaseConnection);

  @override
  _i4.SqlTypes get typeMapping =>
      (super.noSuchMethod(
            Invocation.getter(#typeMapping),
            returnValue: _i11.dummyValue<_i4.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
          )
          as _i4.SqlTypes);

  @override
  _i4.QueryExecutor get executor =>
      (super.noSuchMethod(
            Invocation.getter(#executor),
            returnValue: _FakeQueryExecutor_12(
              this,
              Invocation.getter(#executor),
            ),
          )
          as _i4.QueryExecutor);

  @override
  _i5.StreamQueryStore get streamQueries =>
      (super.noSuchMethod(
            Invocation.getter(#streamQueries),
            returnValue: _FakeStreamQueryStore_13(
              this,
              Invocation.getter(#streamQueries),
            ),
          )
          as _i5.StreamQueryStore);

  @override
  _i4.DatabaseConnectionUser get resolvedEngine =>
      (super.noSuchMethod(
            Invocation.getter(#resolvedEngine),
            returnValue: _FakeDatabaseConnectionUser_14(
              this,
              Invocation.getter(#resolvedEngine),
            ),
          )
          as _i4.DatabaseConnectionUser);

  @override
  _i6.Future<List<_i2.LocalMatchReport>> getMatchesForEvent(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#getMatchesForEvent, [eventId]),
            returnValue: _i6.Future<List<_i2.LocalMatchReport>>.value(
              <_i2.LocalMatchReport>[],
            ),
          )
          as _i6.Future<List<_i2.LocalMatchReport>>);

  @override
  _i6.Future<List<_i2.LocalMatchReport>> getDeletedMatchesForEvent(
    String? eventId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDeletedMatchesForEvent, [eventId]),
            returnValue: _i6.Future<List<_i2.LocalMatchReport>>.value(
              <_i2.LocalMatchReport>[],
            ),
          )
          as _i6.Future<List<_i2.LocalMatchReport>>);

  @override
  _i6.Future<_i2.LocalMatchReport?> getMatch(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMatch, [id]),
            returnValue: _i6.Future<_i2.LocalMatchReport?>.value(),
          )
          as _i6.Future<_i2.LocalMatchReport?>);

  @override
  _i6.Future<List<_i2.LocalMatchReport>> getMatchesByTeamNumber(
    int? teamNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMatchesByTeamNumber, [teamNumber]),
            returnValue: _i6.Future<List<_i2.LocalMatchReport>>.value(
              <_i2.LocalMatchReport>[],
            ),
          )
          as _i6.Future<List<_i2.LocalMatchReport>>);

  @override
  _i6.Future<List<_i2.LocalMatchReport>> getMatchesByTeamNumberForEvent(
    String? eventId,
    int? teamNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMatchesByTeamNumberForEvent, [
              eventId,
              teamNumber,
            ]),
            returnValue: _i6.Future<List<_i2.LocalMatchReport>>.value(
              <_i2.LocalMatchReport>[],
            ),
          )
          as _i6.Future<List<_i2.LocalMatchReport>>);

  @override
  _i6.Future<List<_i2.LocalMatchReport>> searchMatches(
    String? eventId,
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchMatches, [eventId, query]),
            returnValue: _i6.Future<List<_i2.LocalMatchReport>>.value(
              <_i2.LocalMatchReport>[],
            ),
          )
          as _i6.Future<List<_i2.LocalMatchReport>>);

  @override
  _i6.Future<void> upsertMatch(_i2.LocalMatchReportsCompanion? match) =>
      (super.noSuchMethod(
            Invocation.method(#upsertMatch, [match]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> softDeleteMatch(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#softDeleteMatch, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> restoreMatch(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#restoreMatch, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> permanentlyDeleteMatch(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#permanentlyDeleteMatch, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> markMatchSynced(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#markMatchSynced, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i2.LocalMatchReport>> getUnsyncedMatches() =>
      (super.noSuchMethod(
            Invocation.method(#getUnsyncedMatches, []),
            returnValue: _i6.Future<List<_i2.LocalMatchReport>>.value(
              <_i2.LocalMatchReport>[],
            ),
          )
          as _i6.Future<List<_i2.LocalMatchReport>>);

  @override
  _i6.Future<List<_i2.LocalEvent>> getAllEvents() =>
      (super.noSuchMethod(
            Invocation.method(#getAllEvents, []),
            returnValue: _i6.Future<List<_i2.LocalEvent>>.value(
              <_i2.LocalEvent>[],
            ),
          )
          as _i6.Future<List<_i2.LocalEvent>>);

  @override
  _i6.Future<_i2.LocalEvent?> getEvent(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getEvent, [id]),
            returnValue: _i6.Future<_i2.LocalEvent?>.value(),
          )
          as _i6.Future<_i2.LocalEvent?>);

  @override
  _i6.Future<void> upsertEvent(_i2.LocalEventsCompanion? event) =>
      (super.noSuchMethod(
            Invocation.method(#upsertEvent, [event]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteEvent(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEvent, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<int> addToSyncQueue(_i2.SyncQueueCompanion? entry) =>
      (super.noSuchMethod(
            Invocation.method(#addToSyncQueue, [entry]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<List<_i2.SyncQueueData>> getPendingSyncOperations() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingSyncOperations, []),
            returnValue: _i6.Future<List<_i2.SyncQueueData>>.value(
              <_i2.SyncQueueData>[],
            ),
          )
          as _i6.Future<List<_i2.SyncQueueData>>);

  @override
  _i6.Future<List<_i2.SyncQueueData>> getSyncOperationsForEntity(
    String? entityType,
    String? entityId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSyncOperationsForEntity, [
              entityType,
              entityId,
            ]),
            returnValue: _i6.Future<List<_i2.SyncQueueData>>.value(
              <_i2.SyncQueueData>[],
            ),
          )
          as _i6.Future<List<_i2.SyncQueueData>>);

  @override
  _i6.Future<void> completeSyncOperation(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#completeSyncOperation, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateSyncOperationRetry(
    int? id, {
    required int? retryCount,
    String? errorMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateSyncOperationRetry,
              [id],
              {#retryCount: retryCount, #errorMessage: errorMessage},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearAllSyncOperations() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllSyncOperations, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearFailedSyncOperations({int? maxRetries = 10}) =>
      (super.noSuchMethod(
            Invocation.method(#clearFailedSyncOperations, [], {
              #maxRetries: maxRetries,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i2.SyncQueueData>> getFailedSyncOperations({
    int? maxRetries = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFailedSyncOperations, [], {
              #maxRetries: maxRetries,
            }),
            returnValue: _i6.Future<List<_i2.SyncQueueData>>.value(
              <_i2.SyncQueueData>[],
            ),
          )
          as _i6.Future<List<_i2.SyncQueueData>>);

  @override
  _i6.Future<int> recordConflict(_i2.SyncConflictsCompanion? conflict) =>
      (super.noSuchMethod(
            Invocation.method(#recordConflict, [conflict]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<List<_i2.SyncConflict>> getUnresolvedConflicts() =>
      (super.noSuchMethod(
            Invocation.method(#getUnresolvedConflicts, []),
            returnValue: _i6.Future<List<_i2.SyncConflict>>.value(
              <_i2.SyncConflict>[],
            ),
          )
          as _i6.Future<List<_i2.SyncConflict>>);

  @override
  _i6.Future<void> resolveConflict(int? id, String? resolution) =>
      (super.noSuchMethod(
            Invocation.method(#resolveConflict, [id, resolution]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearResolvedConflicts({
    Duration? olderThan = const Duration(days: 30),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#clearResolvedConflicts, [], {
              #olderThan: olderThan,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<int> getMatchCount() =>
      (super.noSuchMethod(
            Invocation.method(#getMatchCount, []),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> getMatchCountForEvent(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#getMatchCountForEvent, [eventId]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> getUnsyncedCount() =>
      (super.noSuchMethod(
            Invocation.method(#getUnsyncedCount, []),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> getTrashCount(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#getTrashCount, [eventId]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<_i2.SyncQueueStats> getSyncQueueStats() =>
      (super.noSuchMethod(
            Invocation.method(#getSyncQueueStats, []),
            returnValue: _i6.Future<_i2.SyncQueueStats>.value(
              _FakeSyncQueueStats_15(
                this,
                Invocation.method(#getSyncQueueStats, []),
              ),
            ),
          )
          as _i6.Future<_i2.SyncQueueStats>);

  @override
  _i6.Future<int> purgeOldDeletedMatches({
    Duration? olderThan = const Duration(days: 30),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#purgeOldDeletedMatches, [], {
              #olderThan: olderThan,
            }),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<void> clearAllData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllData, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i4.Migrator createMigrator() =>
      (super.noSuchMethod(
            Invocation.method(#createMigrator, []),
            returnValue: _FakeMigrator_16(
              this,
              Invocation.method(#createMigrator, []),
            ),
          )
          as _i4.Migrator);

  @override
  _i6.Future<void> beforeOpen(
    _i4.QueryExecutor? executor,
    _i4.OpeningDetails? details,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#beforeOpen, [executor, details]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Ret> computeWithDatabase<Ret, DB extends _i4.GeneratedDatabase>({
    required _i6.FutureOr<Ret> Function(DB)? computation,
    required DB Function(_i4.DatabaseConnection)? connect,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#computeWithDatabase, [], {
              #computation: computation,
              #connect: connect,
            }),
            returnValue:
                _i11.ifNotNull(
                  _i11.dummyValueOrNull<Ret>(
                    this,
                    Invocation.method(#computeWithDatabase, [], {
                      #computation: computation,
                      #connect: connect,
                    }),
                  ),
                  (Ret v) => _i6.Future<Ret>.value(v),
                ) ??
                _FakeFuture_17<Ret>(
                  this,
                  Invocation.method(#computeWithDatabase, [], {
                    #computation: computation,
                    #connect: connect,
                  }),
                ),
          )
          as _i6.Future<Ret>);

  @override
  _i6.Stream<T> createStream<T extends Object>(
    _i5.QueryStreamFetcher<T>? stmt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createStream, [stmt]),
            returnValue: _i6.Stream<T>.empty(),
          )
          as _i6.Stream<T>);

  @override
  T alias<T, D>(_i4.ResultSetImplementation<T, D>? table, String? alias) =>
      (super.noSuchMethod(
            Invocation.method(#alias, [table, alias]),
            returnValue: _i11.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
          )
          as T);

  @override
  void markTablesUpdated(Iterable<_i4.TableInfo<_i4.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(#markTablesUpdated, [tables]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i4.TableUpdate>? updates) => super.noSuchMethod(
    Invocation.method(#notifyUpdates, [updates]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Stream<Set<_i4.TableUpdate>> tableUpdates([
    _i4.TableUpdateQuery? query = const _i4.TableUpdateQuery.any(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#tableUpdates, [query]),
            returnValue: _i6.Stream<Set<_i4.TableUpdate>>.empty(),
          )
          as _i6.Stream<Set<_i4.TableUpdate>>);

  @override
  _i6.Future<T> doWhenOpened<T>(
    _i6.FutureOr<T> Function(_i4.QueryExecutor)? fn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#doWhenOpened, [fn]),
            returnValue:
                _i11.ifNotNull(
                  _i11.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_17<T>(this, Invocation.method(#doWhenOpened, [fn])),
          )
          as _i6.Future<T>);

  @override
  _i4.InsertStatement<T, D> into<T extends _i4.Table, D>(
    _i4.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#into, [table]),
            returnValue: _FakeInsertStatement_18<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
          )
          as _i4.InsertStatement<T, D>);

  @override
  _i4.UpdateStatement<Tbl, R> update<Tbl extends _i4.Table, R>(
    _i4.TableInfo<Tbl, R>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [table]),
            returnValue: _FakeUpdateStatement_19<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
          )
          as _i4.UpdateStatement<Tbl, R>);

  @override
  _i4.SimpleSelectStatement<T, R> select<T extends _i4.HasResultSet, R>(
    _i4.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#select, [table], {#distinct: distinct}),
            returnValue: _FakeSimpleSelectStatement_20<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
          )
          as _i4.SimpleSelectStatement<T, R>);

  @override
  _i4.JoinedSelectStatement<T, R> selectOnly<T extends _i4.HasResultSet, R>(
    _i4.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            returnValue: _FakeJoinedSelectStatement_21<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
          )
          as _i4.JoinedSelectStatement<T, R>);

  @override
  _i4.BaseSelectStatement<_i4.TypedResult> selectExpressions(
    Iterable<_i4.Expression<Object>>? columns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#selectExpressions, [columns]),
            returnValue: _FakeBaseSelectStatement_22<_i4.TypedResult>(
              this,
              Invocation.method(#selectExpressions, [columns]),
            ),
          )
          as _i4.BaseSelectStatement<_i4.TypedResult>);

  @override
  _i4.DeleteStatement<T, D> delete<T extends _i4.Table, D>(
    _i4.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [table]),
            returnValue: _FakeDeleteStatement_23<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
          )
          as _i4.DeleteStatement<T, D>);

  @override
  _i6.Future<int> customUpdate(
    String? query, {
    List<_i4.Variable<Object>>? variables = const [],
    Set<_i4.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i4.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customUpdate,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> customInsert(
    String? query, {
    List<_i4.Variable<Object>>? variables = const [],
    Set<_i4.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customInsert,
              [query],
              {#variables: variables, #updates: updates},
            ),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<List<_i4.QueryRow>> customWriteReturning(
    String? query, {
    List<_i4.Variable<Object>>? variables = const [],
    Set<_i4.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i4.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customWriteReturning,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i6.Future<List<_i4.QueryRow>>.value(<_i4.QueryRow>[]),
          )
          as _i6.Future<List<_i4.QueryRow>>);

  @override
  _i4.Selectable<_i4.QueryRow> customSelect(
    String? query, {
    List<_i4.Variable<Object>>? variables = const [],
    Set<_i4.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelect,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_24<_i4.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i4.Selectable<_i4.QueryRow>);

  @override
  _i4.Selectable<_i4.QueryRow> customSelectQuery(
    String? query, {
    List<_i4.Variable<Object>>? variables = const [],
    Set<_i4.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelectQuery,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_24<_i4.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i4.Selectable<_i4.QueryRow>);

  @override
  _i6.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
            Invocation.method(#customStatement, [statement, args]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<T> transaction<T>(
    _i6.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transaction,
              [action],
              {#requireNew: requireNew},
            ),
            returnValue:
                _i11.ifNotNull(
                  _i11.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_17<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
          )
          as _i6.Future<T>);

  @override
  _i6.Future<T> exclusively<T>(_i6.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#exclusively, [action]),
            returnValue:
                _i11.ifNotNull(
                  _i11.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_17<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
          )
          as _i6.Future<T>);

  @override
  _i6.Future<void> batch(_i6.FutureOr<void> Function(_i4.Batch)? runInBatch) =>
      (super.noSuchMethod(
            Invocation.method(#batch, [runInBatch]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<T> runWithInterceptor<T>(
    _i6.Future<T> Function()? action, {
    required _i4.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runWithInterceptor,
              [action],
              {#interceptor: interceptor},
            ),
            returnValue:
                _i11.ifNotNull(
                  _i11.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_17<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
          )
          as _i6.Future<T>);

  @override
  _i4.GenerationContext $write(
    _i4.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$write,
              [component],
              {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_25(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
          )
          as _i4.GenerationContext);

  @override
  _i4.GenerationContext $writeInsertable(
    _i4.TableInfo<_i4.Table, dynamic>? table,
    _i4.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_25(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i4.GenerationContext);

  @override
  String $expandVar(int? start, int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#$expandVar, [start, amount]),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
          )
          as String);
}
