// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr4V3jaguRFJNwDhYnq7iAsYtjcyXULgg',
    appId: '1:80003441956:web:7a9c9742f18839fa603fb1',
    messagingSenderId: '80003441956',
    projectId: 'sushiscout26-a8f5d',
    authDomain: 'sushiscout26-a8f5d.firebaseapp.com',
    storageBucket: 'sushiscout26-a8f5d.firebasestorage.app',
    measurementId: 'G-EQSB2BWYF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAttKTvyC0zREXX5wlHngi5w-Q5Ed02m2c',
    appId: '1:80003441956:android:bfe1e1f14b06a1ab603fb1',
    messagingSenderId: '80003441956',
    projectId: 'sushiscout26-a8f5d',
    storageBucket: 'sushiscout26-a8f5d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9JIBqNTgYVFfW2kmf2-AFpiJIIeVsBBg',
    appId: '1:80003441956:ios:84dc2be7256d0949603fb1',
    messagingSenderId: '80003441956',
    projectId: 'sushiscout26-a8f5d',
    storageBucket: 'sushiscout26-a8f5d.firebasestorage.app',
    iosBundleId: 'com.sushiscout.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9JIBqNTgYVFfW2kmf2-AFpiJIIeVsBBg',
    appId: '1:80003441956:ios:84dc2be7256d0949603fb1',
    messagingSenderId: '80003441956',
    projectId: 'sushiscout26-a8f5d',
    storageBucket: 'sushiscout26-a8f5d.firebasestorage.app',
    iosBundleId: 'com.sushiscout.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr4V3jaguRFJNwDhYnq7iAsYtjcyXULgg',
    appId: '1:80003441956:web:7a9c9742f18839fa603fb1',
    messagingSenderId: '80003441956',
    projectId: 'sushiscout26-a8f5d',
    authDomain: 'sushiscout26-a8f5d.firebaseapp.com',
    storageBucket: 'sushiscout26-a8f5d.firebasestorage.app',
    measurementId: 'G-EQSB2BWYF3',
  );
}
